ReseauPsy/Models/Therapist/AddAppointmentInfos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ReseauPsy.Models.Therapist
{
    public class AddAppointmentInfos
    {
        public int ClientId { get; set; }
        public string StartDate { get; set; }
        public string TimeStart { get; set; }
        public decimal NbSession { get; set; }
        public int? WageId { get; set; }
        public int NatureActId { get; set; }
        public int ProfessionnalTitleId { get; set; }
        public int ConsultationTypeId { get; set; }
        public bool IsRepetition { get; set; }
        public int? RepeatEveryNumber { get; set; }
        public string RepeatEveryPeriod { get; set; }
        public int? RepeatAmount { get; set; }
        public List<int> RepeatDays { get; set; }

    }
}

ReseauPsy/Controllers/Therapist/Api/AppointmentCalendarController.cs
using Business;
using Library.Helper;
using Microsoft.AspNet.Identity;
using ReseauPsy.Models;
using ReseauPsy.Models.Therapist;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ReseauPsy.Controllers.Therapist.Api
{
    [Authorize(Roles = RoleName.Therapist)]
    public class AppointmentCalendarController : ApiController
    {
        #region Database context

        private ReseauPsyEntities _context;

        public AppointmentCalendarController()
        {
            _context = new ReseauPsyEntities();
        }

        #endregion

        #region Therapist

        public string TherapistIdentityId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        public Business.Therapist TherapistObject
        {
            get
            {
                return _context.Therapists
                    .Where(x => x.AspNetUserId == TherapistIdentityId)
                    .First();
            }
        }


        #endregion

        //GET /api/AppointmentCalendar?start=2021-10-10&end=2021-10-16
        public IEnumerable<AppointmentCalendarModel> GetAppointments(string start, string end)
        {
            var isFrench = CultureInfo.CurrentCulture.Name == "fr-CA";
            var startDate = DateTime.Parse(start, null, System.Globalization.DateTimeStyles.RoundtripKind);
            var endDate = DateTime.Parse(end, null, System.Globalization.DateTimeStyles.RoundtripKind);

            var appointments = new List<AppointmentCalendarModel>();

            var clientAppointments = _context.ClientAppointments
                .Where(x => x.TherapistId == TherapistObject.Id &&
                    !x.IsDeleted &&
                    x.StartDateTime >= startDate &&
                    x.EndDateTime <= endDate)
                .ToList();


            foreach (var appointment in clientAppointments)
            {
                var clientInfos = new GetClientInfos(_context, appointment.ClientId);
                clientInfos.GetMostRecentClientInfo();

                appointments.Add(new AppointmentCalendarModel
                {
                    title = $"{clientInfos.FirstName.Decode()} {clientInfos.LastName.Decode()}",
                    start = appointment.StartDateTime.ToString("yyyy-MM-ddTHH:mm:ss"),
                    end = appointment.EndDateTime.ToString("yyyy-MM-ddTHH:mm:ss"),
                    editable = appointment.StartDateTime > DateTime.Now,

                    extendedProps = new AppointmentCalendarExtendedProposModel
                    {
                        ClientId = appointment.ClientId,
                        AppointmentId = appointment.Id,
                        RepetitionId = appointment.RepetitionId,
                        IsEditable = appointment.StartDateTime > DateTime.Now,
                        IsDurationEditable = !appointment.ClientBillGeneratedDate.HasValue,
                    }
                });
            }

            return appointments;
        }
    }
}

ReseauPsy/Controllers/Therapist/Api/AppointmentModalController.cs
using Business;
using Microsoft.AspNet.Identity;
using ReseauPsy.Models;
using ReseauPsy.Models.Therapist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ReseauPsy.Controllers.Therapist.Api
{
    [Authorize(Roles = RoleName.Therapist)]
    public class AppointmentModalClientInfosController : ApiController
    {
        #region Database context

        private ReseauPsyEntities _context;

        public AppointmentModalClientInfosController()
        {
            _context = new ReseauPsyEntities();
        }

        #endregion

        #region Therapist

        public string TherapistIdentityId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        public Business.Therapist TherapistObject
        {
            get
            {
                return _context.Therapists
                    .Where(x => x.AspNetUserId == TherapistIdentityId)
                    .First();
            }
        }


        #endregion

        //GET /api/AppointmentModalClientInfos?clientid=XX&isFrench=
        public AppointmentModalModel GetClientInfos(int clientId, bool isFrench)
        {
            return new AppointmentModalModel(_context, clientId, isFrench);
        }

    }

    //[Authorize(Roles = RoleName.Therapist)]
    public class AppointmentModalAppointmentInfosController : ApiController
    {
        #region Database context

        private ReseauPsyEntities _context;

        public AppointmentModalAppointmentInfosController()
        {
            _context = new ReseauPsyEntities();
        }

        #endregion

        #region Therapist

        public string TherapistIdentityId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        public Business.Therapist TherapistObject
        {
            get
            {
                return _context.Therapists
                    .Where(x => x.AspNetUserId == TherapistIdentityId)
                    .First();
            }
        }


        #endregion

        //GET /api/AppointmentModalAppointmentInfos?appointmentid=&isFrench=
        public AppointmentModalAppointmentInfos GetAppointmentInfo(int appointmentId, bool isFrench)
        {
            return new AppointmentModalAppointmentInfos(_context, appointmentId, isFrench);
        }
    }
}

ReseauPsy/Controllers/Therapist/Api/GetClientTherapistController.cs
using Business;
using Library.Helper;
using Microsoft.AspNet.Identity;
using ReseauPsy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ReseauPsy.Controllers.Therapist.Api
{
    [Authorize(Roles = RoleName.Therapist)]
    public class GetClientTherapistController : ApiController
    {
        #region Database context

        private ReseauPsyEntities _context;

        public GetClientTherapistController()
        {
            _context = new ReseauPsyEntities();
        }

        #endregion

        [HttpGet]
        public IEnumerable<GetListClientNameSuggestion_Result> GetClientSuggestion(string textEntered)
        {
            string userIdentity = User.Identity.GetUserId();

            var therapist =  _context.Therapists
                .Where(x => x.AspNetUserId == userIdentity)
                .First();

            var clients = _context.GetListClientNameSuggestion(
                textEntered.ToLower(),
                therapist.Id)
                .ToList();

            foreach (var client in clients)
            {
                client.ClientName = client.ClientName.Decode();
            }
            return clients;
        }
    }
}

ReseauPsy/Controllers/Therapist/TherapistController.cs
using Business;
using ReseauPsy.ViewModel.Therapist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ReseauPsy.Models;
using Library.Helper;
using ReseauPsy.ViewModel.Admin;
using ReseauPsy.Models.Therapist;
using System.Globalization;
using HelpersLibrary;
using OfficeOpenXml;
using ReseauPsy.Resources;
using System.Resources;
using System.IO;
using TuesPechkin;
using System.Drawing.Printing;
using ReseauPsy.PDF.Configuration;
using System.Web.Routing;

namespace ReseauPsy.Controllers.Therapist
{
    [Authorize(Roles = RoleName.Therapist)]
    [RedirectAttribute]
    public class TherapistController : Controller
    {

        private ReseauPsyEntities _context;

        //Constructor
        public TherapistController()
        {
            _context = new ReseauPsyEntities();
        }


        private Business.Therapist _therapistObject
        {
            get
            {
                string userIdentity = User.Identity.GetUserId();
                return _context.Therapists
                    .Where(x => x.AspNetUserId == userIdentity)
                    .First();
            }
        }

        private int _nbResultPerPage
        {
            get
            {
                return WebSiteProperties.NbResultPerPage;
            }
        }

        #region Mon profil

        // GET: Therapist
        public ActionResult MyProfile()
        {
            var viewModel = new MyProfileViewModel(_context, _therapistObject);
            return View("MyProfile", viewModel);
        }

        public ActionResult ModifyProfile(TherapistProfileDatas datas)
        {
            #region Verify datas

            if (datas.LastName.Trim() == "" ||
                datas.FirstName.Trim() == "" ||
                datas.Email.Trim() == "" ||
                datas.PhoneNumber.Trim() == "" ||
                datas.Adress.Trim() == "" ||
                datas.City.Trim() == "" ||
                datas.PostalCode.Trim() == "")
            {
                throw new Exception();
            }

            if ((datas.AccreditationId == 1 || datas.AccreditationId == 2) && datas.OpqNumber.Trim() == "")
            {
                throw new Exception();
            }

            var therapistInfo = new GetTherapistInfo(_context, _therapistObject.Id);
            therapistInfo.GetMostRecentTherapistInfo();

            if (therapistInfo.IsTaxable && (datas.TpsNumber.Trim() == "" || datas.TvqNumber.Trim() == ""))
            {
                throw new Exception();
            }

            #endregion

            datas.TherapistId = _therapistObject.Id;

            #region On verifie le courriel

            if (therapistInfo.Email != datas.Email)
            {
                //On change le email. On doit vérifier si le nouveau courriel n'est pas en utilisation
                if (!VerifyIdentityEmail.VerifyEmailAvailabillity(_context, datas.Email))
                {
                    //Le courriel est deja en utilisation, on renvoie le form
                    return Json(new { success = false, error = "EmailUsed" });
                }
            }

            #endregion

            bool isRedirectToDashboard = false;

            if (!_context.VerifiyIfTherapistInscriptionCompleted(_therapistObject.Id)
                .Select(x => x.IsInscriptionCompleted)
                .First())
            {
                isRedirectToDashboard = true;
            }

            var editProdile = new EditProfile(datas, _context, _therapistObject);
            if (!editProdile.Succeeded)
            {
                //La modification du thérapeute a échoué, on renvoie le form
                throw new Exception();
            }

            if (isRedirectToDashboard)
                return Json(new { result = "Redirect", url = Url.Action("Dashboard", "therapist") });

            return Json(new { success = true });
        }
        #endregion

        #region Mes competences

        public ActionResult MySkills()
        {
            var viewModel = new MySkillsViewModel(_context, _therapistObject);
            return View("MySkills", viewModel);
        }

        [HttpPost]
        public ActionResult AddAssociation(string associationNameNumber)
        {
            var association = new TherapistAssociationAndProfessionalOrder();
            association.Therapist = _therapistObject;

            var associationNameNumberSplitted = associationNameNumber.Split(
                new string[] { "--split--" },
                StringSplitOptions.None);

            association.AssociationName = associationNameNumberSplitted[0];
            association.AssociationNumber = associationNameNumberSplitted[1];
            association.CreateDate = DateTime.Now;
            _therapistObject.TherapistAssociationAndProfessionalOrders.Add(association);
            try
            {
                _context.SaveChanges();

                return Json(new { associationId = association.Id });
            }
            catch (Exception)
            {

                return Json(new { msg = "failed" });
            }
        }

        [HttpPost]
        public ActionResult DeleteAssociation(int therapistAssociationId)
        {

            var association = _context.TherapistAssociationAndProfessionalOrders
                .Single(x => x.Id == therapistAssociationId);

            association.DeleteDate = DateTime.Now;

            try
            {
                _context.SaveChanges();
                return Json(new { msg = "success" });
            }
            catch (Exception)
            {
                return Json(new { msg = "failed" });
            }
        }

        [HttpPost]
        public ActionResult ModifyAssociation(int therapistAssociationId, string associationNameNumber)
        {
            var association = _context.TherapistAssociationAndProfessionalOrders
                .Single(x => x.Id == therapistAssociationId);

            association.DeleteDate = DateTime.Now;

            var associationNameNumberSplitted = associationNameNumber.Split(
                new string[] { "--split--" },
                StringSplitOptions.None);

            var newAssociation = new TherapistAssociationAndProfessionalOrder();
            newAssociation.Therapist = _therapistObject;
            newAssociation.AssociationName = associationNameNumberSplitted[0];
            newAssociation.AssociationNumber = associationNameNumberSplitted[1];
            newAssociation.CreateDate = DateTime.Now;

            _therapistObject.TherapistAssociationAndProfessionalOrders.Add(newAssociation);
            try
            {
                _context.SaveChanges();
                return Json(new { msg = "success" });
            }
            catch (Exception)
            {
                return Json(new { msg = "failed" });
            }
        }


        [HttpPost]
        public ActionResult AddService(int serviceId, string serviceTypeIds)
        {
            int[] typeIds = Array.ConvertAll(serviceTypeIds.Split(','), s => int.Parse(s));
            foreach (var typeId in typeIds)
            {
                var offeredserviceofferedservicetype = _context.OfferedService_OfferedServiceType
                    .Where(x => x.OfferedServiceId == serviceId && x.OfferedServiceTypeId == typeId)
                    .Single();

                var therpistOfferedService = new TherapistOfferedService();
                therpistOfferedService.Therapist = _therapistObject;
                therpistOfferedService.OfferedService_OfferedServiceType = offeredserviceofferedservicetype;
                _therapistObject.TherapistOfferedServices.Add(therpistOfferedService);
            }

            try
            {
                _context.SaveChanges();
                return Json(new { msg = "success" });
            }
            catch (Exception)
            {
                return Json(new { msg = "Failed" });
            }
        }

        [HttpPost]
        public ActionResult DeleteService(int serviceId, string serviceTypeIds)
        {
            int[] typeIds = Array.ConvertAll(serviceTypeIds.Split(','), s => int.Parse(s));

            foreach (var typeId in typeIds)
            {
                var offeredserviceofferedservicetype = _context.OfferedService_OfferedServiceType
                    .Where(x => x.OfferedServiceId == serviceId && x.OfferedServiceTypeId == typeId)
                    .Single();

                var therapistService = _context.TherapistOfferedServices
                    .Where(x => x.TherapistId == _therapistObject.Id && x.OfferedService_OfferedServiceTypeId == offeredserviceofferedservicetype.Id)
                    .SingleOrDefault();

                _context.TherapistOfferedServices.Remove(therapistService);
            }

            try
            {
                _context.SaveChanges();
                return Json(new { msg = "success" });
            }
            catch (Exception)
            {
                return Json(new { msg = "Failed" });
            }
        }

        [HttpPost]
        public ActionResult ModifyService(int previousServiceId, string previousServiceTypeIds, int serviceId, string serviceTypeIds)
        {
            int[] previousTypeIds = Array.ConvertAll(previousServiceTypeIds.Split(','), s => int.Parse(s));

            foreach (var typeId in previousTypeIds)
            {
                var offeredserviceofferedservicetype = _context.OfferedService_OfferedServiceType
                    .Where(x => x.OfferedServiceId == previousServiceId && x.OfferedServiceTypeId == typeId)
                    .Single();

                var therapistService = _context.TherapistOfferedServices
                    .Where(x => x.TherapistId == _therapistObject.Id && x.OfferedService_OfferedServiceTypeId == offeredserviceofferedservicetype.Id)

ReseauPsy/Views/Therapist/ConfirmPresence.cshtml
@model ReseauPsy.ViewModel.Therapist.ConfirmPresenceViewModel
@using ReseauPsy.Resources
@{
    ViewBag.Title = Resource.ConfirmPresence_Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <section id="page-therapist-confirmpresence">

        @* Page title *@
        <h1>@Resource.ConfirmPresence_H1 </h1>


        @* Table *@

        <div id="js-confirm-presence-table" class="table-responsive @(Model.Clients.Count>0 ?"" : "d-none")">

            <table style="min-width:400px;">
                <thead>
                    <tr>
                        <th style="width:140px;">@Global.Client</th>
                        <th style="width:120px;">@Global.AppointmentDate</th>
                        <th style="width:140px;" class="text-end">@Resource.ConfirmPresence_PresenceToConfirm</th>
                    </tr>
                </thead>

                <tbody id="js-confirm-presence-table-body">
                    @foreach (var client in Model.Clients)
                    {
                        <tr>
                            <td style="max-width: 140px;">@client.ClientName</td>
                            <td style="max-width: 120px;">@client.AppointmentDateTime.ToString("dd MMM yyyy")</td>
                            <td style="max-width: 140px;" class="text-end">
                                <input class="js-confirm-presence-appointment-id" type="hidden" value="@client.AppointmentId" />
                                <div class="btn btn-primary js-confirm-presence-present">@Global.Yes</div>
                                <div class="btn btn-primary js-confirm-presence-not-present">@Global.No</div>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>

        <div id="js-therapist-presence-empty" class="alert alert-info @(Model.Clients.Count>0 ?"d-none" : "")">
            @Resource.ConfirmPresence_AllConfirmedMessage
        </div>



        @* administrative charge Modal *@



        <div id="AdministrativeChargeModal" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@Resource.ConfirmPresence_ModalAnnulationFees_Title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal">
                            <i class="far fa-times-circle"></i>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-12">
                                @Resource.ConfirmPresence_ModalAnnulationFees_Message
                            </div>

                            <div class="col-6">
                                <div class="form-group">
                                    <label>Appliquer les frais?</label>
                                    <select id="js-confirm-presence-modal-apply-charge-select" class="form-select">
                                        <option value="null">Choisir</option>
                                        <option value="yes">@Global.Apply</option>
                                        <option value="no">@Global.No</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button id="js-close-administrative-modal-button" type="button" class="btn btn-secondary">@Global.Cancel</button>
                        <button id="js-apply-administrative-charge-modal-button" type="button" class="btn btn-primary">@Global.Apply</button>
                    </div>
                </div>
            </div>
        </div>


    </section>
</div>


@section scripts
{
    <script>

        function SavePresenceInDb() {
            var tableRow;
            var appointmentId;
            var applySelect = $("#js-confirm-presence-modal-apply-charge-select");
            var modalId = $("#AdministrativeChargeModal")
            var tableBody = $('#js-confirm-presence-table-body')

            //Open the administrative charge modal
            $(".js-confirm-presence-not-present").on("click", function () {
                appointmentId = $(this).parent().children(".js-confirm-presence-appointment-id").val()
                tableRow = $(this).closest("tr")

                //reset the ddl and error class
                applySelect.val("null");
                applySelect.removeClass("input-validation-error");

                OpenModal(modalId)
            })

            //Close the administrative charge modal
            $("#js-close-administrative-modal-button").on("click", function () {
                closeAdministrativeChargeModal()
            })

            function closeAdministrativeChargeModal() {
                appointmentId = null;

                //Close modal
                closeModal(modalId)
            }


            //Confirm the presence
            $(".js-confirm-presence-present").on("click", function () {
                appointmentId = $(this).parent().children(".js-confirm-presence-appointment-id").val()
                tableRow = $(this).closest("tr");
                SavePresenceInDb();
            })

            //Confirm not present
            $("#js-apply-administrative-charge-modal-button").on("click", function () {

                var isApplyCharge = false;

                //Verfify if there a choice in the ddl
                if (applySelect.val() == "null") {
                    applySelect.addClass("input-validation-error");
                    return false
                }
                else if (applySelect.val() == "yes") {
                    isApplyCharge = true;
                }

                SavePresenceInDb(isApplyCharge);

            })


            applySelect.on("change", function () {
                $(this).removeClass("input-validation-error");
                if ($(this).val() == "null") {
                    $(this).addClass("input-validation-error");
                }
            });


            function SavePresenceInDb(isApplyCharge) {
                //isApplyCharge: undefined -> client was present -> id = 5
                //isApplyCharge: true -> apply admin charges -> id = 4
                //isApplyCharge: false -> dont apply admin charge -> id = 3
                var statusId;


                if (isApplyCharge == true)
                    statusId = 4
                else if (isApplyCharge == false)
                    statusId = 3
                else if (isApplyCharge == undefined)
                    statusId = 5

                $.ajax({
                    type: "POST",
                    url: "/fr/therapist/ConfirmPresenceChangeStatus/",
                    data: `{"appointmentId":"${appointmentId}",
                            "statusId":"${statusId}"}`,
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        tableRow.remove();
                        closeAdministrativeChargeModal()

                        if ($('#js-confirm-presence-table-body tr').length == 0) {
                            //The table is empty, add the no more request message

                            $("#js-confirm-presence-table").addClass("d-none");
                            $("#js-therapist-presence-empty").removeClass("d-none");

                        }

                        toastr["success"]
                            ("@Resource.ConfirmPresence_ToastrSuccess_Message",
                                "@Global.Success");

                    },
                    error: function () {
                        toastr["error"]
                            ("@Global.GenericError",
                                "@Global.Error");



                    }
                })
            }
        }

        SavePresenceInDb();

    </script>
}

ReseauPsy/Views/Therapist/Dashboard.cshtml
@model ReseauPsy.ViewModel.Therapist.DashboardTherapistViewModel
@using ReseauPsy.Resources
@{
    ViewBag.Title = Resource.TherapistDashBoard_Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <section id="page-therapist-dashboard">

        <h1>@Resource.TherapistDashBoard_H1</h1>


        <div class="row">

            @* Appointment requests *@
            <div class="col-12 col-md-4">
                <div class="white-card">
                    <h3>Demandes</h3>
                    <div class="big-number">@Model.AppointmentRequestCount</div>
                    <div class="card-info">Demandes à traiter</div>
                    <a href="@Url.Action("TherapistClientRequest","Therapist")" class="btn btn-primary">@Global.View</a>
                </div>
            </div>

            @* Claimable appointment *@
            <div class="col-12 col-md-4">
                <div class="white-card">
                    <h3>Réclamations</h3>
                    <div class="big-number">@Model.ClaimableAppointmentCount</div>
                    <div class="card-info">Rendez-vous à réclamer</div>
                    <a href="@Url.Action("ClaimForm","Therapist")" class="btn btn-primary">@Global.View</a>
                </div>
            </div>

            @* Appointment request *@
            <div class="col-12 col-md-4">
                <div class="white-card">
                    <h3>Présences</h3>
                    <div class="big-number">@Model.ConfirmPresenceCount</div>
                    <div class="card-info">Présence(s) à confirmer</div>
                    <a href="@Url.Action("ConfirmPresence","Therapist")" class="btn btn-primary">@Global.View</a>
                </div>
            </div>

        </div>


        <div class="row">

            <div class="col-12">
                <div class="white-card">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-12 col-md-6">
                            <div class="row align-items-center">
                                <div class="d-none d-md-block col-md-4">
                                    <img src="/_assets/img/icons/next-rendez-vous.svg" class="icon100" />
                                </div>
                                <div class="col-12 col-md-8">
                                    <h3>Prochains rendez-vous</h3>
                                </div>
                            </div>

                        </div>

                        <div class="col-12 col-md-6 next-detail">

                            @if (Model.IncomingAppointments.Count > 0)
                            {
                                foreach (var appointment in Model.IncomingAppointments)
                                {
                                    <div class="client-detail">@appointment.AppointmentDate.ToString("dd MMM HH:mm") - <strong>@appointment.ClientName</strong></div>
                                }
                            }
                            else
                            {
                                <div>Vous n'avez aucun rendez-vous à venir</div>
                            }
                            <a href="@Url.Action("Appointment","Therapist")" class="btn btn-primary">@Resource.TherapistDashBoard_SeeAll</a>

                        </div>
                    </div>

                </div>
            </div>
        </div>

    </section>
</div>